http:
  middlewares:
    # auth:
    #   basicAuth:
    #     users:
    #       - "admin:htpasswdencryptedpassword"
    https-whitelist:
      ipWhiteList:
        sourceRange:
          # - "192.168.0.0/24" #LAN
          - "127.0.0.1/32" #localhost
          - "172.0.0.0/8" #docker
          - "212.106.107.142/32"
          - "82.127.139.210/32"
    https-redirect:
      redirectScheme:
        scheme: https
        permanent: true
